### ISSUE TITLE
java.util.concurrent.RejectedExecutionException ScheduledThreadPoolExecutor

### ISSUE THREAD

**Issue by AnthonyKoueik** [bertrandmartel/speed-test-lib#17]
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@90a731a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@8a11e4b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
    at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:305)
    at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
    at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:625)
    at fr.bmartel.speedtest.SpeedTestSocket.connectAndExecuteTask(SpeedTestSocket.java:319)
    at fr.bmartel.speedtest.SpeedTestSocket.writeUpload(SpeedTestSocket.java:859)
    at fr.bmartel.speedtest.SpeedTestSocket.startUpload(SpeedTestSocket.java:846)
    at com.koa.test.speedtest.FixedTimeUploadThead.run(FixedTimeUploadThead.java:194)
```

**Comment by bertrandmartel** [comment]
Hello, it seems you dont have the latest version. I remember it was a bug in an old release. Can you test with most recent version (`1.23`) ?

**Comment by bertrandmartel** [comment]
I'm closing this, if you still have the issue with the current version, please reopen.
