### ISSUE TITLE
Crash when uploading(set file size)

### ISSUE THREAD

**Issue by DimaDDM** [bertrandmartel/speed-test-lib#27]
For example. When i'm trying upload 100MB file app catch OOM.
 
FATAL EXCEPTION: pool-7-thread-1
                                                                           java.lang.OutOfMemoryError
                                                                               at fr.bmartel.speedtest.utils.RandomGen.generateRandomArray(RandomGen.java:59)
                                                                               at fr.bmartel.speedtest.SpeedTestTask$7.run(SpeedTestTask.java:990)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                               at java.lang.Thread.run(Thread.java:856)

**Comment by bertrandmartel** [comment]
This is because the random byte array to be uploaded is generated before the upload start, to avoid the generation to be included into the speed test time. 

I could create some chunks of random byte array before each socket write and exclude the time taken by the generation of these array but it would imply to suspend the speed test timing (and should still be compatible with fixed upload time). 

Thank you for reporting this, I will try to find a way to deal with both issues

**Comment by DimaDDM** [comment]
Thanks
