### ISSUE TITLE
java.lang.OutOfMemoryError in generateRandomArray() 

### ISSUE THREAD

**Issue by joearkay** [bertrandmartel/speed-test-lib#34]
Exception in thread "pool-12981-thread-1" java.lang.OutOfMemoryError: Java heap space
	at fr.bmartel.speedtest.utils.RandomGen.generateRandomArray(RandomGen.java:59)
	at fr.bmartel.speedtest.SpeedTestTask$1.run(SpeedTestTask.java:253)
	at fr.bmartel.speedtest.SpeedTestTask$3.run(SpeedTestTask.java:425)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Running on a Raspberry Pi 2

**Comment by joearkay** [comment]
@bertrandmartel seems to occur at line 59: `final byte[] buffer = new byte[length];`

**Comment by bertrandmartel** [comment]
Hello, this is the same as #27 I will fix this asap

**Comment by joearkay** [comment]
Brilliant, thank you!

**Comment by DimaDDM** [comment]
We waiting for a new version!

**Comment by bertrandmartel** [comment]
I noticed that it would be more convenient to use file storage rather than doing that dynamically, can you test with : 
```
speedTestSocket.setUploadStorageType(UploadStorageType.FILE_STORAGE);
```
before launching upload, it will store the data to upload in a file and pick to it rather than using `UploadStorageType.RAM_STORAGE` which is the default

**Comment by bertrandmartel** [comment]
@DimaDDM upgraded `commons-net` to 3.6, thanks

**Comment by joearkay** [comment]
@bertrandmartel fantastic! Let us know when you have locked the next update version :)

**Comment by bertrandmartel** [comment]
1.26 is now available on Jcenter & Maven Central
