### ISSUE TITLE
Possible java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DimaDDM** [bertrandmartel/speed-test-lib#48]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.fastRemove(ArrayList.java:531)
       at java.util.ArrayList.remove(ArrayList.java:514)
       at fr.bmartel.speedtest.SpeedTestSocket.initReportTask(Unknown Source)
       at fr.bmartel.speedtest.RepeatWrapper.getRepeatReport$1869eac7(Unknown Source)
       at fr.bmartel.speedtest.RepeatWrapper$1.onCompletion(Unknown Source)
       at fr.bmartel.speedtest.utils.SpeedTestUtils.dispatchError(Unknown Source)
       at fr.bmartel.speedtest.SpeedTestTask.setReportInterval(Unknown Source)
       at fr.bmartel.speedtest.SpeedTestTask$2.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by bertrandmartel** [comment]
Can you show your code ?

**Comment by DimaDDM** [comment]
It's crash report. I can't get more information from crashlytics and can't reproduce on my Android device >_<
I will try send more information as soon as possible. Thanks for new verion :)
