### ISSUE TITLE
ConcurrentModificationException Error

### ISSUE THREAD

**Issue by librushi** [bertrandmartel/speed-test-lib#67]
Hello, 

i need you help with this error, can you help me

![image](https://user-images.githubusercontent.com/26982288/45206209-1fe47980-b28d-11e8-86b0-bd1989df3122.png)

**Comment by DimaDDM** [comment]
![9i1ewps62fs](https://user-images.githubusercontent.com/4531719/51446132-cb630780-1d1e-11e9-8302-50ae39d14ae8.jpg)

`java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:831)
at fr.bmartel.speedtest.RepeatWrapper.getRepeatReport(RepeatWrapper.java:157)
at fr.bmartel.speedtest.SpeedTestTask.getReport(SpeedTestTask.java:1001)
at fr.bmartel.speedtest.SpeedTestSocket.getLiveReport(SpeedTestSocket.java:445)
at fr.bmartel.speedtest.RepeatWrapper$3.run(RepeatWrapper.java:266)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)`

I still have same problem too.
