### ISSUE TITLE
Eclipse: java.lang.NoClassDefFoundError: fr/bmartel/speedtest/inter/ISpeedTestListener

### ISSUE THREAD

**Issue by EngineerBarsik** [bertrandmartel/speed-test-lib#87]
Imported JAR of the library and got this error. Full:

Exception in thread "main" java.lang.NoClassDefFoundError: fr/bmartel/speedtest/inter/ISpeedTestListener
	at MainClass.main(MainClass.java:7)
Caused by: java.lang.ClassNotFoundException: fr.bmartel.speedtest.inter.ISpeedTestListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 1 more

**Comment by EngineerBarsik** [comment]
I'm getting no errors before compiling. In the process of compiling it shows up
